services:
  - type: web
    name: lostfound-portal
    env: python
    buildCommand: "./build.sh"
    startCommand: "./start.sh"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DEBUG
        value: "True"
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
