# Generated by Django 6.0.4 on 2026-04-21 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_alter_claim_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='status',
            field=models.CharField(default='active', max_length=10),
        ),
    ]
