# Generated by Django 6.0.4 on 2026-04-23 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_item_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='is_seen',
            field=models.BooleanField(default=False),
        ),
    ]
